### ISSUE TITLE
Amend to existing README.md

### ISSUE THREAD

**Issue by binarykitchen** [pgilad/gulp-todo#16]
I love this module, very useful - many thanks!

Do you think another option to amend the TODO to an existing README.md would be possible?

(or can I embed the TODO.md into the README.md somehow?)

**Comment by thoroc** [comment]
Hi ,

Just tried this code almost verbatim 
``` js
gulp.task('todo', function () {
    var todo = require('gulp-todo');
    var through = require('through2');
    var _ = require('lodash');
    var template = _.template;
    var fs = require('fs');
    var path = require('path');

    gulp.src('./gulp/**/*.js')
        .pipe(todo())
        .pipe(through.obj(function (file, enc, cb) {
            //read and interpolate template
            var newContents = template(fs.readFileSync('./readme.md.template'), {
                marker: file.contents.toString()
            });
            //change file name
            file.path = path.join(file.base, 'readme-new.md');
            //replace old contents
            file.contents = new Buffer(newContents);
            //push new file
            this.push(file);
            cb();
        }))
        .pipe(gulp.dest('./'));
});
```
I am getting I am getting an error with the ```new Buffer```. I am guessing [```Buffer```](https://nodejs.org/api/buffer.html) must have changed since then. I might use the gulp-template plugin as suggested, but I am a bit at loss why creating the ```Buffer``` object would have changed.

For ref here is the error reported when running the task:

```
buffer.js:67
    throw new TypeError('must start with number, buffer, array or string');
          ^
TypeError: must start with number, buffer, array or string
    at new Buffer (buffer.js:67:11)
    at DestroyableTransform._transform (E:\Projects\github-rx\gulpfile.js:73:29)
    at DestroyableTransform.Transform._read (E:\Projects\github-rx\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (E:\Projects\github-rx\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (E:\Projects\github-rx\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (E:\Projects\github-rx\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (E:\Projects\github-rx\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at write (E:\Projects\github-rx\node_modules\gulp-todo\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (E:\Projects\github-rx\node_modules\gulp-todo\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (E:\Projects\github-rx\node_modules\gulp-todo\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:664:5)
```

**Comment by pgilad** [comment]
@thoroc Can you specify what you pass with `newContents` to `new Buffer()` ?

My guess is it's a function and not a string... Make sure to pass a string to it. If the code doesn't work, let me know so I can update it.

**Comment by thoroc** [comment]
Oh I never used [lodash.template](https://lodash.com/docs#template) before. I thought naively that it was returning a string ....

**Comment by thoroc** [comment]
Right splitting the code and adding some ```console.log()``` calls:

``` js
gulp.task('todo-old', function () {
   var template = './readme.md.template';
    return gulp.src(source)
        .pipe(todo())
        .pipe(through.obj(function (file, enc, cb) {
            //read and interpolate template
            var tpl = fs.readFileSync(template)
            console.log(Object.prototype.toString.call(tpl));

            var newContents = _.template(tpl, {
                marker: file.contents.toString()
            });
            console.log(Object.prototype.toString.call(newContents));

            //change file name
            file.path = path.join(file.base, 'README.md');
            //replace old contents
            file.contents = new Buffer(newContents);
            //push new file
            this.push(file);
            cb();
        }))
        //        .pipe($.rename('README..md'))
        .pipe(gulp.dest('../'));
});
```

The output is the following: 
```
[object Object]
[object Function]
```

So yes the ```newContents``` appears to be a function and not just merely a string as I assumed.

**Comment by pgilad** [comment]
I see. The problem is with this line:
`var tpl = fs.readFileSync(template);`
By default it reads the file as a buffer. You need to write:
`var tpl = fs.readFileSync(template, 'utf8');`

That should fix it
